
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("POSTGRES_USER") { '' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { '' } %>
  host:     <%= ENV.fetch("POSTGRES_HOST") { '' } %>
  port:     <%= ENV.fetch("POSTGRES_PORT") { '' } %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  variables:
    statement_timeout: '<%= $PROGRAM_NAME.include?("puma") ? "30s" : "300s" %>'

development:
  <<: *default
  database: nexus_development

test:
  <<: *default
  database: nexus_test
  advisory_locks: false

production:
  <<: *default
  database: nexus_production
  url: <%= ENV['DATABASE_URL'] %>
